# .air.toml
root = "."
tmp_dir = "tmp"

[build]
bin = "tmp/main"
cmd = "go build -o tmp/main cmd/ledger/main.go"
include = ["*.go"]
exclude = ["tmp", "vendor"]
log = "air.log"

[color]
main = "yellow"
watcher = "cyan"
build = "green"
log = "white"