run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 2
  tests: false

output:
  print-issued-lines: false
  print-linter-name: true
  uniq-by-line: false
  path-prefix: ""
  sort-results: true

linters-settings:
  golint:
    min-confidence: 0
  maligned:
    suggest-new: true
  dupl:
    threshold: 120
  goconst:
    min-len: 2
    min-occurrences: 2
  gofmt:
    rewrite-rules:
      - pattern: 'interface{}'
        replacement: 'any'
      - pattern: 'a[b:len(a)]'
        replacement: 'a[b:]'
  gosec:
    excludes:
      - G401
      - G501
      - G106
      - G505
  gocritic:
    disabled-checks:
      - ifElseChain

linters:
  enable:
    - errcheck
    - gosimple
    - ineffassign
    - staticcheck
    - unused
    - govet
    - decorder
    - dogsled
    - dupword
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - forbidigo
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocritic
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - grouper
    - importas
    - inamedparam
    - interfacebloat
    - intrange
    - lll
    - loggercheck
    - makezero
    - misspell
    - musttag
    - nakedret
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - rowserrcheck
    - sloglint
    - spancheck
    - stylecheck
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
    - wsl
    - zerologlint

issues:
  exclude-dirs:
    - vendor
  exclude-rules:
    - linters:
        - lll
      source: '`.*validate:".*"`'
    - linters:
        - lll
      path: "environments/.*"